"""Interactive CLI setup to wrap/unwrap MCP servers with token-sieve compression."""

from __future__ import annotations

import json
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

CONFIGS_DIR = "~/.token-sieve/configs"


@dataclass
class McpServerEntry:
    """A single MCP server entry parsed from a config file."""

    name: str
    command: str
    args: list[str] = field(default_factory=list)
    env: dict[str, str] = field(default_factory=dict)

    @property
    def is_wrapped(self) -> bool:
        """True if this server is already wrapped by token-sieve."""
        return self.command in ("token-sieve", "token-smithers")


@dataclass
class McpConfigFile:
    """An MCP configuration file with its parsed server entries."""

    path: Path
    scope: str  # "project" or "global"
    servers: list[McpServerEntry] = field(default_factory=list)
    raw_data: dict = field(default_factory=dict)


def _parse_servers(data: dict) -> list[McpServerEntry]:
    """Parse mcpServers dict into McpServerEntry list."""
    entries: list[McpServerEntry] = []
    mcp_servers = data.get("mcpServers", {})
    for name, cfg in mcp_servers.items():
        entries.append(
            McpServerEntry(
                name=name,
                command=cfg.get("command", ""),
                args=cfg.get("args", []),
                env=cfg.get("env", {}),
            )
        )
    return entries


def discover_mcp_configs(
    project_dir: Path | None = None,
) -> list[McpConfigFile]:
    """Find MCP config files in project directory and user home.

    Args:
        project_dir: Directory to search for .mcp.json. Defaults to cwd.

    Returns:
        List of discovered config files with parsed server entries.
    """
    configs: list[McpConfigFile] = []

    # Project-level .mcp.json
    proj = (project_dir or Path.cwd()) / ".mcp.json"
    if proj.exists():
        data = json.loads(proj.read_text())
        configs.append(
            McpConfigFile(
                path=proj,
                scope="project",
                servers=_parse_servers(data),
                raw_data=data,
            )
        )

    # Global ~/.claude.json
    global_path = Path.home() / ".claude.json"
    if global_path.exists():
        data = json.loads(global_path.read_text())
        if data.get("mcpServers"):
            configs.append(
                McpConfigFile(
                    path=global_path,
                    scope="global",
                    servers=_parse_servers(data),
                    raw_data=data,
                )
            )

    return configs


def generate_sieve_config(server: McpServerEntry) -> str:
    """Generate YAML config content for a token-sieve wrapper.

    Args:
        server: The original server entry to wrap.

    Returns:
        YAML string with backend config referencing the original server.
    """
    args_str = " ".join(server.args)
    header = (
        f"# Auto-generated by token-sieve setup\n"
        f"# Original: {server.command} {args_str}\n"
    )

    backend: dict = {
        "command": server.command,
        "args": server.args,
    }
    if server.env:
        backend["env"] = server.env

    config = {"backend": backend}
    return header + yaml.dump(config, default_flow_style=False)


def wrap_servers(
    config_file: McpConfigFile,
    server_names: list[str],
    configs_dir: str,
) -> list[str]:
    """Wrap selected servers with token-sieve in the config.

    Creates YAML config files in configs_dir and modifies raw_data in-place.
    Does NOT write the config file to disk.

    Args:
        config_file: The MCP config file to modify.
        server_names: Names of servers to wrap.
        configs_dir: Directory to write per-server YAML configs.

    Returns:
        List of server names that were wrapped.
    """
    configs_path = Path(configs_dir)
    configs_path.mkdir(parents=True, exist_ok=True)

    wrapped: list[str] = []
    server_map = {s.name: s for s in config_file.servers}

    for name in server_names:
        server = server_map.get(name)
        if server is None or server.is_wrapped:
            continue

        # Write YAML config
        yaml_path = configs_path / f"{name}.yaml"
        yaml_path.write_text(generate_sieve_config(server))

        # Update raw_data
        yaml_abs = str(yaml_path.resolve())
        config_file.raw_data["mcpServers"][name] = {
            "command": "token-smithers",
            "args": ["--config", yaml_abs],
        }

        # Update server entry
        server.command = "token-smithers"
        server.args = ["--config", yaml_abs]

        wrapped.append(name)

    return wrapped


def unwrap_servers(
    config_file: McpConfigFile,
    configs_dir: str,
) -> list[str]:
    """Unwrap token-sieve wrapped servers back to their originals.

    Reads YAML configs to restore original command/args/env.

    Args:
        config_file: The MCP config file to modify.
        configs_dir: Directory where per-server YAML configs are stored.

    Returns:
        List of server names that were unwrapped.
    """
    unwrapped: list[str] = []

    for server in config_file.servers:
        if not server.is_wrapped:
            continue

        # Find the --config path from args
        config_path = None
        for i, arg in enumerate(server.args):
            if arg == "--config" and i + 1 < len(server.args):
                config_path = Path(server.args[i + 1])
                break

        if config_path is None or not config_path.exists():
            continue

        # Read original backend from YAML
        data = yaml.safe_load(config_path.read_text())
        backend = data.get("backend", {})

        original_cmd = backend.get("command", "")
        original_args = backend.get("args", [])
        original_env = backend.get("env", {})

        # Restore raw_data
        restored: dict = {
            "command": original_cmd,
            "args": original_args,
        }
        if original_env:
            restored["env"] = original_env
        config_file.raw_data["mcpServers"][server.name] = restored

        # Update server entry
        server.command = original_cmd
        server.args = original_args
        server.env = original_env

        unwrapped.append(server.name)

    return unwrapped


def backup_config(path: Path) -> Path:
    """Create a backup of the config file.

    Args:
        path: Path to the config file.

    Returns:
        Path to the backup file.
    """
    backup_path = path.with_suffix(path.suffix + ".backup")
    shutil.copy2(path, backup_path)
    return backup_path


def write_config(config_file: McpConfigFile) -> None:
    """Write the modified config back to disk.

    Preserves all non-mcpServers keys from raw_data.

    Args:
        config_file: The config file with updated raw_data.
    """
    config_file.path.write_text(
        json.dumps(config_file.raw_data, indent=2) + "\n"
    )


def run_setup(undo: bool = False) -> int:
    """Interactive setup runner.

    Args:
        undo: If True, unwrap all token-sieve wrapped servers.

    Returns:
        0 on success, 1 on error.
    """
    configs = discover_mcp_configs()
    if not configs:
        print(
            "No MCP config files found (.mcp.json or ~/.claude.json).",
            file=sys.stderr,
        )
        return 1

    configs_dir = str(Path(CONFIGS_DIR).expanduser())

    if undo:
        return _run_undo(configs, configs_dir)
    return _run_wrap(configs, configs_dir)


def _run_undo(configs: list[McpConfigFile], configs_dir: str) -> int:
    """Unwrap all wrapped servers."""
    total_unwrapped: list[str] = []

    for cf in configs:
        unwrapped = unwrap_servers(cf, configs_dir)
        if unwrapped:
            backup_config(cf.path)
            write_config(cf)
            total_unwrapped.extend(unwrapped)

    if not total_unwrapped:
        print("No wrapped servers found to undo.")
        return 0

    print(f"Unwrapped {len(total_unwrapped)} server(s): {', '.join(total_unwrapped)}")
    print()
    print('  "Smithers, you\'re fired." — Token compression disabled.')
    print("  Your MCP servers are back to their original configuration.")
    return 0


def _run_wrap(configs: list[McpConfigFile], configs_dir: str) -> int:
    """Interactive server wrapping."""
    # Collect all unwrapped servers
    available: list[tuple[McpConfigFile, McpServerEntry]] = []
    already_wrapped: list[str] = []

    for cf in configs:
        for srv in cf.servers:
            if srv.is_wrapped:
                already_wrapped.append(srv.name)
            else:
                available.append((cf, srv))

    if not available:
        if already_wrapped:
            print(
                f"All servers already wrapped: {', '.join(already_wrapped)}"
            )
        else:
            print("No servers found in config files.")
        return 0

    # Display available servers
    print("Available MCP servers:\n")
    for i, (cf, srv) in enumerate(available, 1):
        print(f"  {i}. [{cf.scope}] {srv.name} ({srv.command} {' '.join(srv.args)})")

    if already_wrapped:
        print(f"\n  Already wrapped: {', '.join(already_wrapped)}")

    print("\nEnter server numbers (comma-separated) or 'all': ", end="")
    sys.stdout.flush()
    user_input = input().strip()

    if not user_input:
        print("No servers selected.")
        return 0

    # Parse selection
    if user_input.lower() == "all":
        selected = list(range(len(available)))
    else:
        try:
            selected = [int(x.strip()) - 1 for x in user_input.split(",")]
            for idx in selected:
                if idx < 0 or idx >= len(available):
                    print(f"Invalid selection: {idx + 1}", file=sys.stderr)
                    return 1
        except ValueError:
            print("Invalid input. Enter numbers or 'all'.", file=sys.stderr)
            return 1

    # Group by config file
    by_config: dict[Path, tuple[McpConfigFile, list[str]]] = {}
    for idx in selected:
        cf, srv = available[idx]
        if cf.path not in by_config:
            by_config[cf.path] = (cf, [])
        by_config[cf.path][1].append(srv.name)

    # Wrap servers
    total_wrapped: list[str] = []
    for cf, names in by_config.values():
        backup_config(cf.path)
        wrapped = wrap_servers(cf, names, configs_dir)
        write_config(cf)
        total_wrapped.extend(wrapped)

    print(f"\nWrapped {len(total_wrapped)} server(s): {', '.join(total_wrapped)}")
    print(f"Configs written to: {configs_dir}")
    print()
    print('  "Release the hounds!" — Token compression is now active.')
    print("  Use Claude Code normally. Check savings with: token-smithers stats")
    return 0
